dist: trusty
language: node_js

node_js:
  - stable

install:
  - npm install

addons:
  sonarcloud:
    organization: "deependrax-github"
    token:
      secure: "B0jB32vAnsIRjS3pAvZgl+Om9AAT91lw9f0t1v5xxo/r6HG+D4V8hbwoY5FnQg3PSc2QGAtT8o42MgFJayDYeT9IAuxiAlRkFyfx0eWCwnXz+K3T7Vx+NQcutWfWA2SeKs99QqYtLC5lrEodB4VtBLx7k48/Q5x6ammDD3b+xQGHx5Hl0ONLEurNO9uE2BxRzAp6IydZtRi69dqL8gdgfyWdB3d/EOjWHrs1EFPb3dOOfpxQX6eJQIbEMW6wXGyufdJSCTONMQ5XKQP7QDoxaYcWTA2WON5f1XbJCS+eoe/TGnaSMan5YLrIEYyBpY0zjSXMiaQmHbW+2A03CL4SgHxJR5RJcd7Ck7FpB+6QA/xqdbhFoOhmlrjTQIUEoGcNEqKFk4Y25eLMHdDqK/v3fCEmLhRsA2LvZ7u3EoTLO6bFcAGXVBKRxEgHkEFS51QfWX1cWIbHL8Byr1s7QDbCpSBBFWIoVWnUsUDsuaVoBuAfElqcqM+oBxAXTpVyE1cNbM5VnBUDk/KLDrpjJxxJjargoZIBN09DkxTwLJriTRgg6QHXlQWxw0PqIlAzbmaOCrUTqKcTDZ/7qIetbqgCR9CA0mlM93RBzBw1LYmQgh8pnJIU/hRHDN/XRSlZHuvqQotif4fYgFKqKonMxlFr4z7t9E+Yn4C8zHG9s95iJgc="
      
script:
  - npm test
  - sonar-scanner
  

# Send coverage data to Coveralls
after_success: npm run coverage